jquery_lang_js.prototype.lang.es = {
	'Sensor House':'Home',
	'Conozcanos':'Sensor House',
	'Informacion General':'At a Glance',
        'Presentacion':'Corporate Governance',
	'Objetivos':'What Matters Most',
        'Competencias':'Leadership',
	'Garantia de Calidad':'Code of Conduct',
	'Video Vigilancia':'Security Systems',
	'Nuestro Modelo':'How It Works',
        'Nuestros Paquetes':'Security Systems',
	'Paquete Conectes':'Basic Plan',
	'Paquete Acerques':'Silver Plan',
	'Paquete Alejes':'Golden Plan',
	'Clientes':'My Account',
	'Tienda':'Shop Now',
	'Nota Legal':'Legal',
	'Contactanos':'Contact Us',
	'Mis Camara':'Live Cam',
	'Mis Fotos':'My Media',
	'Desconectar':'Logout',
	'Soporte':'Help',
	'Usuarios':'Users',
	'Planes':'Solutions',
	'Fotos':'Pictures',
	'Land':'ที่ดินว่างเปล่า',
	'Anytime':'แสดงผลทั้งหมด',
	'Last 3 Days':'วันที่ผ่านมา',
	'Last Week':'สัปดาห์ที่ผ่านมา',
	'Last Month':'เดือนที่ผ่านมา',
	'Loading':'กำลังประมวลผล',
	'My Saved Searches':'การค้นหาที่ถูกเก็บไว้',
	'My Listings':'รายการของฉัน',
	'My Analytics':'สถิติผู้เข้าชมประกาศของฉัน',
	'Create New Listing':'ลงประกาศ',
	'View My Account':'ดูข้อมูลของฉัน',
	'Property Listing Details':'รายละเอียดประกาศ',
	'Listing Type':'ชนิดของประกาศ',
	'Sell':'ขาย',
	'Let':'เช่า',
	'Lease':'เซ้ง',
	'Floors':'ชั้น',
	
	
	'Leasehold':'มีระยะสัญญา',
	'Possession':'บ้านว่างหรือไม่',
	'Onward Chain':'มีผู้อาศัยอยู่',
	'Vacant Possession':'บ้านว่างพร้อมเข้าอยู่ทันที',
	'Property Location':'สถานที่ตั้ง',
	'Country':'ประเทศ',
	'Post/Zip Code':'รหัสไปรษณีย์',
	'No.':'เลขที่',
	'Road Name':'ชื่อถนน',
	'County/Province':'จังหวัด',
	'Town/City':'อำเภอ',
	'Lease Years Remaining':'จำนวนปีของสัญญาที่เหลือ',
	'day':'วัน',
	'week':'สัปดาห์',
	'month':'เดือน',
	'quarter':'3 เดือน',
	'year':'ปี',
	'Submit Your Listing':'ลงประกาศ',
	'Upload Image':'ใส่รูป',
	'Finish':'เสร็จเรียบร้อย',
	'Search':'ค้นหา',
	'Search...':'ค้นหา',
	'Property Description':'รายละเอียดของประกาศ',
	'Synopsis':'รายละเอียดย่อในประกาศ',
	'Full Description':'รายละเอียดเพิ่มเติมสำหรับผู้สนใจประกาศ',
	'Property Photos':'รูปภาพสถานที่',
}